import { useEffect, useState } from "react";
import { buildMarkdownReport } from "@/domain/report/markdown";

type Snapshot = { instrumentId: string; title: string; definitionVersion: string; appVersion: string; completedAt: number; results: Array<{ title: string; score: number; max: number; band: string }>; disclaimer: string; sources: string[]; safetyMessages: string[] };
export default function ResultView() {
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  useEffect(() => { const raw = sessionStorage.getItem("psychekit:last-result"); if (raw) setSnapshot(JSON.parse(raw)); }, []);
  if (!snapshot) return <div className="panel"><h1>Brak bieżącego wyniku</h1><p>Wynik pojawi się tutaj po ukończeniu kwestionariusza. Nie jest zapisywany automatycznie w historii.</p><a href="/">Wybierz kwestionariusz</a></div>;
  const markdown = buildMarkdownReport({ ...snapshot, date: new Date(snapshot.completedAt).toISOString().slice(0, 10), instrumentVersion: snapshot.definitionVersion });
  const copy = async () => { const prompt = `Pomóż mi opisać poniższe wyniki bez diagnozowania i bez dopowiadania faktów. Zaznacz ograniczenia samoopisu.\n\n${markdown}`; await navigator.clipboard.writeText(prompt); };
  const download = () => { const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${snapshot.instrumentId}-wynik.md`; link.click(); URL.revokeObjectURL(url); };
  return <div className="hero"><p className="eyebrow">Wynik samoopisu</p><h1>{snapshot.title}</h1><p className="meta">Ukończono: {new Date(snapshot.completedAt).toLocaleString("pl-PL")}</p><div className="result-grid">{snapshot.results.map((result) => <article className="card" key={result.title}><h2>{result.title}</h2><p><strong>{result.score} / {result.max}</strong></p><p>Przedział: {result.band}</p></article>)}</div><p className="notice">{snapshot.disclaimer}</p>{snapshot.safetyMessages.map((message) => <div className="notice danger" key={message}><p>{message}</p><p><strong>Bezpośrednie zagrożenie:</strong> <a href="tel:112">112</a></p><p><strong>Całodobowe wsparcie dla dorosłych:</strong> <a href="tel:116123">116 123</a></p><p><strong>Centrum Wsparcia:</strong> <a href="tel:800702222">800 70 2222</a></p><p><strong>Dzieci i młodzież:</strong> <a href="tel:116111">116 111</a></p></div>)}<div className="question-actions"><button type="button" onClick={download}>Pobierz Markdown</button><button className="secondary" type="button" onClick={() => void copy()}>Kopiuj wynik i instrukcję dla AI</button></div><p className="meta">Po wklejeniu do zewnętrznej usługi AI dane opuszczają PsycheKit i podlegają zasadom prywatności tej usługi.</p><h2>Źródła</h2><ul>{snapshot.sources.map((source) => <li key={source}><a href={source}>{source}</a></li>)}</ul></div>;
}
